# Generated by Django 5.0.6 on 2024-07-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='none', upload_to='uploads/category/'),
        ),
    ]
