# Generated by Django 5.0.7 on 2024-08-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='uploads/profile_pics/default.png', null=True, upload_to='uploads/profile_pics/'),
        ),
    ]
